# Generated by Django 4.2 on 2023-04-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_film_created_in_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.ManyToManyField(related_name='film_director', to='films.director'),
        ),
    ]
