# Generated by Django 4.2 on 2023-04-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_alter_vehicle_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
