# Generated by Django 4.2 on 2023-04-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0004_alter_category_gifs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gif',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
