# Generated by Django 4.2 on 2023-04-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0005_alter_gif_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gif',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
